# Generated by Django 5.2.17 on 2026-09-14 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(db_index=True, help_text='The dev_id the terminal sends. Usually the serial printed on the side.', max_length=64, unique=True)),
                ('name', models.CharField(help_text='e.g. Main Gate', max_length=80)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('purpose', models.CharField(choices=[('STUDENT', 'Student attendance'), ('TEACHER', 'Teacher attendance'), ('BOTH', 'Both')], default='STUDENT', max_length=10)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('fk_name', models.CharField(blank=True, max_length=64)),
                ('firmware', models.CharField(blank=True, max_length=64)),
                ('fk_bin_data_lib', models.CharField(blank=True, max_length=64)),
                ('supported_enroll_data', models.JSONField(blank=True, default=list)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('last_device_time', models.CharField(blank=True, max_length=20)),
                ('punch_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name', 'serial_number'],
            },
        ),
        migrations.CreateModel(
            name='TrafficLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('IN', 'Device -> server'), ('OUT', 'Server -> device')], max_length=3)),
                ('dev_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('request_code', models.CharField(blank=True, max_length=40)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('body_preview', models.TextField(blank=True)),
                ('body_size', models.IntegerField(default=0)),
                ('hex_preview', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='UnknownDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=64, unique=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('hit_count', models.PositiveIntegerField(default=1)),
                ('last_request_code', models.CharField(blank=True, max_length=40)),
                ('last_payload', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmd_code', models.CharField(max_length=40)),
                ('cmd_param', models.JSONField(blank=True, default=dict)),
                ('cmd_binary', models.BinaryField(blank=True, null=True)),
                ('status', models.CharField(choices=[('WAIT', 'Waiting'), ('RUN', 'Sent to device'), ('DONE', 'Completed'), ('ERROR', 'Failed')], db_index=True, default='WAIT', max_length=8)),
                ('return_code', models.CharField(blank=True, max_length=64)),
                ('result_json', models.JSONField(blank=True, null=True)),
                ('result_binary', models.BinaryField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='devices.device')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CommandBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blk_no', models.IntegerField()),
                ('data', models.BinaryField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('command', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='devices.devicecommand')),
            ],
            options={
                'ordering': ['blk_no'],
                'unique_together': {('command', 'blk_no')},
            },
        ),
        migrations.CreateModel(
            name='DeviceEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_user_id', models.CharField(max_length=32)),
                ('user_name', models.CharField(blank=True, max_length=120)),
                ('privilege', models.CharField(blank=True, max_length=24)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='enroll/')),
                ('backup_numbers', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='devices.device')),
            ],
            options={
                'ordering': ['device', 'device_user_id'],
                'unique_together': {('device', 'device_user_id')},
            },
        ),
        migrations.CreateModel(
            name='Punch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_user_id', models.CharField(db_index=True, max_length=32)),
                ('punch_time', models.DateTimeField(db_index=True)),
                ('verify_mode', models.CharField(blank=True, help_text='FACE, FP, CARD, PASSWORD ...', max_length=24)),
                ('io_mode', models.CharField(blank=True, help_text='Device in/out flag', max_length=16)),
                ('image', models.ImageField(blank=True, null=True, upload_to='punches/%Y/%m/')),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(db_index=True, default=False)),
                ('process_note', models.CharField(blank=True, max_length=200)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punches', to='devices.device')),
            ],
            options={
                'ordering': ['-punch_time'],
                'indexes': [models.Index(fields=['processed', 'punch_time'], name='devices_pun_process_21ddfe_idx')],
                'unique_together': {('device', 'device_user_id', 'punch_time')},
            },
        ),
    ]
