# Generated by Django 5.2.17 on 2026-09-14 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('body', models.TextField(help_text='Placeholders: {name} {roll} {class} {section} {date} {time} {status} {slot} {guardian} {school}')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SmsSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Absent alert, 9:30', max_length=80)),
                ('audience', models.CharField(choices=[('GUARDIAN', 'Student guardian'), ('STUDENT', "Student's own number"), ('TEACHER', 'Teacher')], default='GUARDIAN', max_length=10)),
                ('statuses', models.JSONField(blank=True, default=list, help_text='Which statuses trigger a message, e.g. ["ABSENT", "LATE"]. Empty means all.')),
                ('send_time', models.TimeField(help_text='Messages go out at this time')),
                ('days', models.JSONField(blank=True, default=list, help_text='Weekday numbers, Monday=0. Empty means every day.')),
                ('colour', models.CharField(default='#8a5a2b', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_slot', models.ForeignKey(blank=True, help_text='Report on this slot only. Leave empty to cover every slot that day.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='attendance.timeslot')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedules', to='smsapp.smstemplate')),
            ],
            options={
                'ordering': ['order', 'send_time', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SmsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msisdn', models.CharField(db_index=True, max_length=20)),
                ('body', models.TextField()),
                ('csms_id', models.CharField(max_length=24, unique=True)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('SKIPPED', 'Skipped')], default='QUEUED', max_length=8)),
                ('for_date', models.DateField(blank=True, db_index=True, null=True)),
                ('reference_id', models.CharField(blank=True, max_length=64)),
                ('error', models.CharField(blank=True, max_length=250)),
                ('response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='academics.student')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='academics.teacher')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='smsapp.smsschedule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SmsRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_date', models.DateField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(default=0)),
                ('sent', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('detail', models.TextField(blank=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='smsapp.smsschedule')),
            ],
            options={
                'ordering': ['-started_at'],
                'unique_together': {('schedule', 'for_date')},
            },
        ),
        migrations.CreateModel(
            name='SmsScheduleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='smsapp.smsschedule')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_schedules', to='academics.section')),
            ],
            options={
                'ordering': ['section__school_class__order', 'section__name'],
                'unique_together': {('schedule', 'section')},
            },
        ),
        migrations.CreateModel(
            name='SmsScheduleTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_targets', to='smsapp.smsschedule')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sms_schedules', to='academics.teacher')),
            ],
            options={
                'unique_together': {('schedule', 'teacher')},
            },
        ),
    ]
