# Generated by Django 5.2.17 on 2026-09-14 05:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. 2026', max_length=40, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('applies_to_teachers', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('designation', models.CharField(blank=True, max_length=80)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('device_user_id', models.CharField(blank=True, db_index=True, help_text='User ID enrolled on the attendance terminal (the number shown on the device).', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_on', models.DateField(default=django.utils.timezone.localdate)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Class Six', max_length=60)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Sort order in lists')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='academics.academicsession')),
            ],
            options={
                'verbose_name_plural': 'School classes',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. A', max_length=30)),
                ('room', models.CharField(blank=True, max_length=40)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='academics.schoolclass')),
            ],
            options={
                'ordering': ['school_class__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ClassAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_edit_attendance', models.BooleanField(default=True)),
                ('can_send_sms', models.BooleanField(default=False)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_access', to='academics.schoolclass')),
                ('section', models.ForeignKey(blank=True, help_text='Leave empty to grant the whole class.', null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.section')),
            ],
            options={
                'verbose_name_plural': 'Class access',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=30, unique=True)),
                ('roll_no', models.CharField(blank=True, max_length=20)),
                ('full_name', models.CharField(max_length=120)),
                ('guardian_name', models.CharField(blank=True, max_length=120)),
                ('guardian_phone', models.CharField(blank=True, help_text='SMS goes here. 01XXXXXXXXX or 8801XXXXXXXXX.', max_length=20)),
                ('student_phone', models.CharField(blank=True, max_length=20)),
                ('device_user_id', models.CharField(blank=True, db_index=True, help_text='User ID enrolled on the attendance terminal.', max_length=32)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='students/')),
                ('is_active', models.BooleanField(default=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academics.section')),
            ],
            options={
                'ordering': ['section__school_class__order', 'section__name', 'roll_no', 'full_name'],
            },
        ),
    ]
