# Generated by Django 5.2.17 on 2026-09-14 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classaccess',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_access', to='academics.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together={('name', 'session')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('school_class', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='classaccess',
            unique_together={('teacher', 'school_class', 'section')},
        ),
    ]
