# Generated by Django 5.2.17 on 2026-09-14 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_group_shift_version_alter_section_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='imports/%Y/%m/')),
                ('original_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('PENDING', 'Waiting for a worker'), ('RUNNING', 'Importing'), ('DONE', 'Finished'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=8)),
                ('dry_run', models.BooleanField(default=False, help_text='Check the file and report problems without writing anything.')),
                ('create_logins', models.BooleanField(default=False, help_text='Also create a student login for each new row.')),
                ('deactivate_missing', models.BooleanField(default=False, help_text='Mark any student not in the file as inactive.')),
                ('total_rows', models.IntegerField(default=0)),
                ('processed', models.IntegerField(default=0)),
                ('created', models.IntegerField(default=0)),
                ('updated', models.IntegerField(default=0)),
                ('skipped', models.IntegerField(default=0)),
                ('deactivated', models.IntegerField(default=0)),
                ('new_classes', models.JSONField(blank=True, default=list)),
                ('new_sections', models.JSONField(blank=True, default=list)),
                ('new_shifts', models.JSONField(blank=True, default=list)),
                ('new_versions', models.JSONField(blank=True, default=list)),
                ('new_groups', models.JSONField(blank=True, default=list)),
                ('problems', models.JSONField(blank=True, default=list)),
                ('error', models.TextField(blank=True)),
                ('task_id', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
