# Generated by Django 5.2.17 on 2026-09-14 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_importjob'),
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='deactivated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='face_detail',
            field=models.CharField(blank=True, help_text='What the terminal reported — which biometric types it stored.', max_length=120),
        ),
        migrations.AddField(
            model_name='student',
            name='face_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='face_enrolments', to='devices.device'),
        ),
        migrations.AddField(
            model_name='student',
            name='face_enrolled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='face_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='face_status',
            field=models.CharField(choices=[('NONE', 'Not enrolled'), ('PENDING', 'Waiting at the terminal'), ('DONE', 'Enrolled')], db_index=True, default='NONE', max_length=8),
        ),
        migrations.AddField(
            model_name='student',
            name='leave_note',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='leave_reason',
            field=models.CharField(blank=True, choices=[('TRANSFERRED', 'Transferred to another school'), ('CANCELLED', 'Admission cancelled'), ('PASSED_OUT', 'Passed out'), ('OTHER', 'Other')], max_length=12),
        ),
        migrations.AddField(
            model_name='student',
            name='left_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='rfid_number',
            field=models.CharField(blank=True, db_index=True, help_text='Card number, if the student carries one.', max_length=32),
        ),
    ]
