# Generated by Django 5.2.17 on 2026-09-21 12:53

from django.db import migrations, models
from django.db.models import F


def roll_from_admission(apps, schema_editor):
    """
    Fill every blank roll with the admission number.

    The first import deliberately left rolls empty, because the old system's
    "Roll No" column held the admission ID. At this school that ID *is* the
    roll, so fill it in — one UPDATE, whatever the size of the roll.
    """
    Student = apps.get_model("academics", "Student")
    Student.objects.filter(roll_no="").update(roll_no=F("admission_no"))


def noop(apps, schema_editor):
    """Nothing to undo: a copied roll is indistinguishable from a typed one."""


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_student_deactivated_by_student_face_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='roll_no',
            field=models.CharField(blank=True, help_text='Any text — digits, letters, dashes. Left blank, the admission number is used.', max_length=40),
        ),
        migrations.RunPython(roll_from_admission, noop),
    ]
