# Generated by Django 5.2.17 on 2026-09-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_roll_no_any_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='kind',
            field=models.CharField(choices=[('STUDENTS', 'Students'), ('TEACHERS', 'Teachers')], db_index=True, default='STUDENTS', max_length=10),
        ),
        migrations.AddField(
            model_name='teacher',
            name='campus',
            field=models.CharField(blank=True, db_index=True, help_text='Which campus or branch, if the school has several.', max_length=60),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='create_logins',
            field=models.BooleanField(default=False, help_text='Also create a login for each new row.'),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='deactivate_missing',
            field=models.BooleanField(default=False, help_text='Mark anyone not in the file as inactive.'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='joined_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
