# Generated by Django 5.2.17 on 2026-09-14 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Morning assembly', max_length=80)),
                ('slot_type', models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher')], db_index=True, default='STUDENT', max_length=10)),
                ('start_time', models.TimeField(help_text='Window opens — punches start counting')),
                ('late_time', models.TimeField(help_text='On or after this, a punch is marked late')),
                ('end_time', models.TimeField(help_text='Window closes — no punch by now means absent')),
                ('out_start_time', models.TimeField(blank=True, help_text='Optional: check-out window opens', null=True)),
                ('out_end_time', models.TimeField(blank=True, help_text='Optional: check-out window closes', null=True)),
                ('days', models.JSONField(blank=True, default=list, help_text='Weekday numbers, Monday=0. Empty means every day.')),
                ('colour', models.CharField(default='#2f6f8f', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', 'start_time', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherAttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent'), ('LEAVE', 'On leave'), ('HOLIDAY', 'Holiday')], db_index=True, max_length=10)),
                ('in_time', models.DateTimeField(blank=True, null=True)),
                ('out_time', models.DateTimeField(blank=True, null=True)),
                ('minutes_late', models.IntegerField(default=0)),
                ('is_manual', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.device')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='academics.teacher')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.timeslot')),
            ],
            options={
                'ordering': ['-date', 'teacher__full_name'],
                'unique_together': {('date', 'teacher', 'time_slot')},
            },
        ),
        migrations.CreateModel(
            name='SlotTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='academics.teacher')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='attendance.timeslot')),
            ],
            options={
                'ordering': ['teacher__full_name'],
                'unique_together': {('time_slot', 'teacher')},
            },
        ),
        migrations.CreateModel(
            name='SlotSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='academics.section')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='attendance.timeslot')),
            ],
            options={
                'ordering': ['section__school_class__order', 'section__name'],
                'unique_together': {('time_slot', 'section')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent'), ('LEAVE', 'On leave'), ('HOLIDAY', 'Holiday')], db_index=True, max_length=10)),
                ('in_time', models.DateTimeField(blank=True, null=True)),
                ('out_time', models.DateTimeField(blank=True, null=True)),
                ('minutes_late', models.IntegerField(default=0)),
                ('is_manual', models.BooleanField(default=False)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='devices.device')),
                ('edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='academics.student')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.timeslot')),
            ],
            options={
                'ordering': ['-date', 'student__section__school_class__order', 'student__roll_no'],
                'indexes': [models.Index(fields=['date', 'status'], name='attendance__date_64c311_idx')],
                'unique_together': {('date', 'student', 'time_slot')},
            },
        ),
    ]
